#!/usr/bin/env node

import { mkdir, readFile, readdir, rename, stat, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { readJson, validateMarketplace, validatePlugin } from "./contracts.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const SUPPORTED_PLATFORMS = new Set(["darwin", "linux"]);

function json(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function yamlString(value) {
  return JSON.stringify(value);
}

function skillYaml(skill) {
  return [
    "# Generated by tools/portability/sync-plugins.mjs. Do not edit.",
    "interface:",
    `  display_name: ${yamlString(skill.displayName)}`,
    `  short_description: ${yamlString(skill.shortDescription)}`,
    `  default_prompt: ${yamlString(skill.defaultPrompt)}`,
    "",
  ].join("\n");
}

function claudeManifest(plugin) {
  const manifest = {
    name: plugin.name,
    displayName: plugin.interface.displayName,
    version: plugin.version,
    description: plugin.description,
    author: plugin.author,
    repository: plugin.repository,
    license: plugin.license,
    keywords: plugin.tags,
  };
  const claudeHooks = plugin.components.hooks?.claude?.manifest;
  if (claudeHooks && claudeHooks !== "hooks/hooks.json") manifest.hooks = `./${claudeHooks}`;
  return manifest;
}

function codexManifest(plugin) {
  const manifest = {
    name: plugin.name,
    version: plugin.version,
    description: plugin.description,
    author: plugin.author,
    repository: plugin.repository,
    license: plugin.license,
    keywords: plugin.tags,
    skills: "./skills/",
    interface: {
      displayName: plugin.interface.displayName,
      shortDescription: plugin.interface.shortDescription,
      longDescription: plugin.interface.longDescription,
      developerName: plugin.interface.developerName,
      category: plugin.category,
      capabilities: plugin.interface.capabilities,
      defaultPrompt: plugin.interface.defaultPrompt,
    },
  };
  if (plugin.components.hooks?.codex) manifest.hooks = `./${plugin.components.hooks.codex.manifest}`;
  return manifest;
}

function hookCommand(host, script) {
  return host === "claude"
    ? `node "\${CLAUDE_PLUGIN_ROOT}/${script}"`
    : `node "$PLUGIN_ROOT/${script}"`;
}

function hooks(host, config) {
  const command = hookCommand(host, config.script);
  const hookMap = {};
  for (const registration of config.registrations) {
    hookMap[registration.event] = [{
      matcher: registration.matcher,
      hooks: [{ type: "command", command, timeout: registration.timeout }],
    }];
  }
  return { hooks: hookMap };
}

async function loadCanonical(root) {
  const marketplaceFile = path.join(root, "marketplace/marketplace.json");
  const marketplace = validateMarketplace(await readJson(marketplaceFile), marketplaceFile);
  const plugins = new Map();
  for (const entry of marketplace.plugins.filter((plugin) => plugin.kind === "local")) {
    const pluginFile = path.join(root, entry.path, "plugin.json");
    const plugin = validatePlugin(await readJson(pluginFile), pluginFile);
    if (plugin.name !== entry.name) throw new Error(`${pluginFile}.name: expected "${entry.name}"`);
    if ([...plugin.hosts].sort().join("\0") !== [...entry.hosts].sort().join("\0")) {
      throw new Error(`${pluginFile}.hosts: must exactly match marketplace hosts`);
    }
    plugins.set(plugin.name, plugin);
  }
  return { marketplace, plugins };
}

export async function buildProjections({ root = ROOT, platform = process.platform } = {}) {
  if (!SUPPORTED_PLATFORMS.has(platform)) {
    throw new Error(`Unsupported platform "${platform}". Bonboncinnabon supports macOS and Linux.`);
  }
  const { marketplace, plugins } = await loadCanonical(root);
  const outputs = new Map();
  const claudePlugins = [];
  const codexPlugins = [];
  for (const entry of marketplace.plugins) {
    if (entry.kind === "external") {
      if (entry.hosts.includes("claude")) claudePlugins.push(entry.claudeEntry);
      continue;
    }
    const plugin = plugins.get(entry.name);
    if (entry.hosts.includes("claude")) {
      claudePlugins.push({
        name: plugin.name,
        version: plugin.version,
        source: entry.path,
        description: plugin.description,
        category: plugin.category.toLowerCase(),
        tags: plugin.tags,
      });
      outputs.set(path.join(entry.path, ".claude-plugin/plugin.json"), json(claudeManifest(plugin)));
    }
    if (entry.hosts.includes("codex")) {
      codexPlugins.push({
        name: plugin.name,
        source: { source: "local", path: entry.path },
        policy: { installation: "AVAILABLE", authentication: "ON_INSTALL" },
        category: plugin.category,
      });
      outputs.set(path.join(entry.path, ".codex-plugin/plugin.json"), json(codexManifest(plugin)));
      for (const skill of plugin.components.skills) {
        outputs.set(path.join(entry.path, `skills/${skill.name}/agents/openai.yaml`), skillYaml(skill));
      }
    }
    if (plugin.components.hooks?.claude) {
      const config = plugin.components.hooks.claude;
      outputs.set(path.join(entry.path, config.manifest), json(hooks("claude", config)));
    }
    if (plugin.components.hooks?.codex) {
      const config = plugin.components.hooks.codex;
      outputs.set(path.join(entry.path, config.manifest), json(hooks("codex", config)));
    }
  }
  outputs.set(
    ".claude-plugin/marketplace.json",
    json({
      $schema: "https://claude.ai/schemas/marketplace.json",
      name: marketplace.name,
      description: marketplace.description,
      owner: marketplace.owner,
      plugins: claudePlugins,
    }),
  );
  outputs.set(
    ".agents/plugins/marketplace.json",
    json({
      name: marketplace.name,
      interface: { displayName: marketplace.displayName },
      plugins: codexPlugins,
    }),
  );
  return outputs;
}

async function atomicWrite(file, content) {
  await mkdir(path.dirname(file), { recursive: true });
  const temporary = `${file}.tmp-${process.pid}`;
  await writeFile(temporary, content);
  await rename(temporary, file);
}

async function exists(file) {
  try {
    await stat(file);
    return true;
  } catch {
    return false;
  }
}

async function generatedCandidates(root) {
  const candidates = new Set([".claude-plugin/marketplace.json", ".agents/plugins/marketplace.json"]);
  const pluginsRoot = path.join(root, "plugins");
  for (const pluginName of await readdir(pluginsRoot)) {
    const pluginRoot = path.join(pluginsRoot, pluginName);
    for (const relative of [
      ".claude-plugin/plugin.json",
      ".codex-plugin/plugin.json",
      "hooks/claude.json",
      "hooks/hooks.json",
      "hooks/codex-hooks.json",
    ]) {
      if (await exists(path.join(pluginRoot, relative))) candidates.add(`plugins/${pluginName}/${relative}`);
    }
    const skillsRoot = path.join(pluginRoot, "skills");
    if (!(await exists(skillsRoot))) continue;
    for (const skillName of await readdir(skillsRoot)) {
      const relative = `plugins/${pluginName}/skills/${skillName}/agents/openai.yaml`;
      if (await exists(path.join(root, relative))) candidates.add(relative);
    }
  }
  return candidates;
}

export async function sync({ root = ROOT, check = false, platform = process.platform } = {}) {
  const outputs = await buildProjections({ root, platform });
  const errors = [];
  for (const [relative, expected] of outputs) {
    const file = path.join(root, relative);
    let actual;
    try {
      actual = await readFile(file, "utf8");
    } catch {
      actual = null;
    }
    if (actual === expected) continue;
    if (check) errors.push(`${relative}: ${actual === null ? "missing" : "stale"}`);
    else await atomicWrite(file, expected);
  }
  for (const relative of await generatedCandidates(root)) {
    if (outputs.has(relative)) continue;
    if (check) errors.push(`${relative}: extra generated projection`);
    else await unlink(path.join(root, relative));
  }
  if (errors.length) throw new Error(errors.join("\n"));
  return { count: outputs.size, check };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  sync({ check: process.argv.includes("--check") })
    .then(({ count, check }) => {
      process.stdout.write(`${check ? "Checked" : "Generated"} ${count} plugin projections.\n`);
    })
    .catch((error) => {
      process.stderr.write(`${error.message}\n`);
      process.exitCode = 1;
    });
}
